spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springcloudexternal
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: USER
    jpa:
      properties:
        hibernate:
          id:
            new_generator_mappings: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://172.20.20.208:8088/realms/springcloud-microservice
          jwk-set-uri: http://172.20.20.208:8088/realms/springcloud-microservice/protocol/openid-connect/certs
  doc:
    swagger-ui:
      oauth:
        client-id: KeycloakSpringClient
        client-secret: KhBJrhQlAjGCnIyAdMbvii8Z7ZGhfZuT


realm: springcloud-microservice
server-url: http://172.20.20.208:8088
client-id: admin-cli
grant-type: password
name: adminuser
password: password
clientName: springboot-application



server:
  port: 8083